// styles/styles.js
// Styles
const styles = {
  header: {
    backgroundColor: '#92400e',
    padding: '0.75rem 1.5rem',
    color: 'white',
  }, headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.5rem',
  },
  headerFlex: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1rem 0',
  },
  logo: {
    fontSize: '1.875rem',
    fontWeight: 'bold',
    background: 'none',
    border: 'none',
    color: 'white',
    cursor: 'pointer',
    transition: 'color 0.2s',
  },
  nav: {
    display: 'flex',
    gap: '1.5rem',
    listStyle: 'none',
  },
  navButton: {
    padding: '0.5rem 1rem',
    borderRadius: '0.375rem',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1rem',
    transition: 'background-color 0.2s',
    color: 'white',
  },
  navButtonActive: {
    backgroundColor: '#d97706',
    fontWeight: '600',
  },
  navButtonInactive: {
    backgroundColor: 'transparent',
  },
  footer: {
    backgroundColor: '#1f2937', // dark gray for contrast
    color: 'white',
    marginTop: 'auto',
    boxShadow: '0 -4px 6px rgba(0,0,0,0.1)',
  },

  footerContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '1.5rem 1rem',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.25rem',
    fontFamily: "'Inter', sans-serif",
  },

  footerLink: {
    color: '#fbbf24',
    textDecoration: 'none',
    fontWeight: '500',
    transition: 'color 0.2s ease, text-shadow 0.2s ease',
    cursor: 'pointer',
    ':hover': {
      color: '#fde68a',
      textShadow: '0 0 4px #facc15',
    },
  },

  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '3rem 1rem',
  },
  homeHero: {
    minHeight: '100vh',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    position: 'relative',
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  heroContent: {
    position: 'relative',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '3rem 1rem',
  },
  heroTitle: {
    fontSize: '3.75rem',
    fontWeight: 'bold',
    color: 'white',
    marginBottom: '1rem',
    textAlign: 'center',
    textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
  },
  heroSubtitle: {
    fontSize: '1.875rem',
    color: 'white',
    marginBottom: '2rem',
    textAlign: 'center',
    textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
  },
  heroImage: {
    width: '100%',
    maxWidth: '64rem',
    margin: '0 auto 3rem',
    borderRadius: '0.5rem',
    boxShadow: '0 20px 25px -5px rgba(0,0,0,0.3)',
  },
  ctaButton: {
    display: 'inline-block',
    backgroundColor: '#d97706',
    color: 'white',
    padding: '1rem 2rem',
    borderRadius: '0.5rem',
    fontSize: '1.25rem',
    fontWeight: '600',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    transition: 'background-color 0.2s',
  },

  // ABOUT PAGE BACKGROUND (uses image from public/images)
  aboutBackground: {
    minHeight: '100vh',
    backgroundImage: "url('/images/jettCookingBeans.jpeg')",
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '3rem 1rem',
  },
  aboutOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.)',
  },
  aboutContainer: {
    position: 'relative',
    maxWidth: '48rem',
    margin: '0 auto',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 1)',
    padding: '2rem',
    zIndex: 1,
  },

  aboutTitle: {
    fontSize: '2.25rem',
    fontWeight: 'bold',
    color: '#92400e',
    marginBottom: '1.5rem',
  },
  aboutText: {
    color: '#374151',
    marginBottom: '1rem',
    lineHeight: '1.75',
  },
  beanGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '1.5rem',
    marginBottom: '3rem',
  },
  beanCard: {
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    overflow: 'hidden',
    transition: 'transform 0.2s ease',
    ':hover': {
      transform: 'translateY(-5px)'
    }
  },
  beanImage: {
    width: '100%',
    height: '12rem',
    objectFit: 'cover',
  },
  beanCardContent: {
    padding: '1.5rem',
  },
  beanName: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: '#92400e',
    marginBottom: '0.5rem',
  },
  beanDescription: {
    color: '#6b7280',
    marginBottom: '1rem',
  },
  beanPrice: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '1rem',
  },
  inputGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  input: {
    flex: 1,
    padding: '0.5rem 0.75rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.375rem',
    fontSize: '1rem',
  },
  addButton: {
    backgroundColor: '#d97706',
    color: 'white',
    padding: '0.5rem 1.5rem',
    borderRadius: '0.375rem',
    border: 'none',
    cursor: 'pointer',
    fontWeight: '600',
    transition: 'background-color 0.2s',
  },
  cartContainer: {
    maxWidth: '48rem',
    margin: '0 auto',
  },
  cartBox: {
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    padding: '1.5rem',
  },
  cartEmpty: {
    backgroundColor: '#f3f4f6',
    borderRadius: '0.5rem',
    padding: '1.5rem',
    textAlign: 'center',
    color: '#6b7280',
    fontSize: '1.125rem',
  },
  cartTitle: {
    fontSize: '1.875rem',
    fontWeight: 'bold',
    color: '#92400e',
    marginBottom: '1.5rem',
  },
  cartItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #e5e7eb',
    paddingBottom: '1rem',
    marginBottom: '1rem',
  },
  cartItemDetails: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  removeButton: {
    color: '#dc2626',
    fontWeight: '600',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  },
  cartTotal: {
    borderTop: '1px solid #e5e7eb',
    paddingTop: '1rem',
    marginBottom: '1.5rem',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '1.25rem',
    fontWeight: 'bold',
  },
  submitButton: {
    width: '100%',
    backgroundColor: '#16a34a',
    color: 'white',
    padding: '0.75rem',
    borderRadius: '0.5rem',
    fontSize: '1.25rem',
    fontWeight: '600',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    transition: 'background-color 0.2s',
  },
  thankYouBox: {
    maxWidth: '32rem',
    margin: '0 auto',
    backgroundColor: '#dcfce7',
    border: '2px solid #16a34a',
    borderRadius: '0.5rem',
    padding: '3rem',
    textAlign: 'center',
  },
  thankYouTitle: {
    fontSize: '2.25rem',
    fontWeight: 'bold',
    color: '#166534',
    marginBottom: '1rem',
  },
};

export default styles;
